---
name: Build artifacts

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create configuration files
        run: |
          echo $NPMRC > .npmrc
          echo $ENV_LOCAL > packages/viewer/.env.local
        env:
          NPMRC: |
            node-linker=hoisted
          ENV_LOCAL: ${{ vars.ENV_LOCAL }}

      - uses: pnpm/action-setup@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Next.js build cache
        uses: actions/cache@v4
        with:
          path: packages/viewer/.next/cache/
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('packages/viewer/**/*.[jt]s', 'packages/viewer/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-
            ${{ runner.os }}-nextjs-

      - name: Build
        run: pnpm -r run build

      # - name: Upload luogu-discussion-archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: luogu-discussion-archive
      #     path: packages/archive/dist/

      # - name: Upload luogu-discussion-viewer
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: luogu-discussion-viewer
      #     path: |
      #       packages/viewer/.next/
      #       !packages/viewer/.next/cache/
